### ISSUE TITLE
obtain permission for tracking and studying participants

### ISSUE THREAD

**Issue by lsetiawan** [geohackweek/administrative#13]
A goal of our previous events was to study the development of a hack week, to observe participant behavior, and quantify the achievement of learning outcomes. 
- [ ] invite social scientists to observe hackweek activities 
- [ ] apply for approval from Internal Review Board 
- [ ] ideally, participants should consent to be contacted at the application stage, which opens up the potential of tracking both participants and non-participants and allows for evaluation of the hack week.

**Comment by aaarendt** [comment]
TODO: 
- [ ] Here's the IRB website for UW: https://www.washington.edu/research/hsd/
- [ ] contact Anissa for help on getting paperwork
